Transition from mailgun org to gubernator-io org
gubernator-io/gubernator pull request #1
Opened 2024-01-24 01:03 UTC by thrawn01

### Purpose
This is to transition the repo from github.com/mailgun/gubernator to github.com/gubernator-io/gubernator such that adding and removing contributors is simplified and does not require access to the mailgun org.

### Implementation
* Transition public container from `ghcr.io/mailgun/gubernator` to `ghcr.io/gubernator-io/gubernator`
* Rename all import paths from `github.com/mailgun/gubernator` to `github.com/gubernator-io/gubernator`
*Ensure links to all external and github resources point to `https://raw.githubusercontent.com/gubernator-io/gubernator/master`

### Manual Process
- [ ] Ensure existing tags remain
- [ ] Create a new release in `github.com/gubernator-io/gubernator` which refers to the old repo release log
- [ ] Transition old container tags to new repo
- [ ] Ensure github actions work as expected

2024-02-01 16:46 UTC, Baliedge requested changes

2024-02-01 16:46 UTC, Baliedge commented on CODE_OF_CONDUCT.md
> +[INSERT CONTACT METHOD].
`[INSERT CONTACT METHOD]`

2024-02-01 16:46 UTC, Baliedge commented on CODE_OF_CONDUCT.md
> +[INSERT CONTACT METHOD].
Who are the "community leaders" and how I do get to be one of these awesome people?

2024-02-01 16:46 UTC, Baliedge commented on go.mod
> +module github.com/gubernator-io/gubernator/v2
Can we do away with `/v2`?

2024-02-01 16:55 UTC, thrawn01 commented on CODE_OF_CONDUCT.md
> +[INSERT CONTACT METHOD].
You are a repo maintainer in GitHub and you are in the code owner file.

2024-02-01 16:57 UTC, thrawn01 commented on go.mod
> +module github.com/gubernator-io/gubernator/v2
I like the idea, but then I would need to clear all the git tags and containers versions. It might be confusing.

2024-02-02 14:59 UTC, Baliedge commented on go.mod
> +module github.com/gubernator-io/gubernator/v2
Then how about `/v3`?

2024-02-02 14:59 UTC, Baliedge commented on CODE_OF_CONDUCT.md
> +[INSERT CONTACT METHOD].
Oh, so I'm already awesome.  Got it. 👍🏻

2024-02-02 18:26 UTC, thrawn01 commented on go.mod
> +module github.com/gubernator-io/gubernator/v2
I'll kick it to v3 when the DUH-RPC stuff drops. 😋

2024-02-02 19:53 UTC, Baliedge approved these changes

2024-02-05 18:01 UTC, thrawn01 commented
I'm holding this PR until we merge and update the other pending PR's on the old repo.

2024-03-22 14:15 UTC, Baliedge commented on benchmark_cache_test.go
> +	"github.com/gubernator-io/gubernator/v2"
Recent versions of golangci-lint complain about this and prefer the explicit import name.

2024-03-22 15:32 UTC, merged